# Generated by Django 3.1.1 on 2020-09-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management_app', '0002_auto_20200920_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavereportdepartment',
            name='leave_status',
            field=models.IntegerField(default=0),
        ),
    ]
