# Generated by Django 3.1.1 on 2020-09-22 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management_app', '0003_auto_20200921_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavereportemployee',
            name='leave_status',
            field=models.IntegerField(default=0),
        ),
    ]
